version: "3.8"

services:
  # 開発用サービス
  dev:
    build:
      context: .
      target: development # Dockerfileのdevelopmentステージを指定
    ports:
      - "8888:8888" # Jupyter Labのポート
    volumes:
      # ローカルのコードをマウントして、変更を即時反映
      - .:/app
      # Hugging Faceのモデルキャッシュを永続化
      - hf_cache:/app/hf_cache
    # GPUを有効化
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # 利用可能な全てのGPUを割り当てる
              capabilities: [gpu]

  # 本番（API）用サービス
  api:
    build:
      context: .
      target: production # Dockerfileのproductionステージを指定
    ports:
      - "8000:8000" # APIサーバーのポート
    volumes:
      # モデルキャッシュのみ永続化（コードはイメージに焼き込み済み）
      - hf_cache:/app/hf_cache
    # 本番環境でもGPUを有効化する場合
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# Dockerが管理する名前付きボリュームを定義
volumes:
  hf_cache:
